require("zanthrash.plugins-setup")
require("zanthrash.core.keymaps")
require("zanthrash.core.options")
require("zanthrash.core.colorscheme")
require("zanthrash.plugins.autopairs")
require("zanthrash.plugins.comment")
require("zanthrash.plugins.neotree")
require("zanthrash.plugins.nvim-cmp")
require("zanthrash.plugins.treesitter")
require("zanthrash.plugins.telescope")
require("zanthrash.plugins.neotest")
require("zanthrash.plugins.lualine")
require("zanthrash.plugins.gitsigns")
require("zanthrash.plugins.colorizer")

require("zanthrash.plugins.lsp.mason")
require("zanthrash.plugins.lsp.lspsaga")
require("zanthrash.plugins.lsp.lspconfig")
require("zanthrash.plugins.lsp.null-ls")

-- require("zanthrash.set")
--require("zanthrash.remap")
